apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.server.port }}
        env:
        # Application
        - name: ENV
          value: {{ .Values.env | quote }}
        # HTTP server
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: {{ .Values.server.port | quote }}
        - name: SERVER_READ_TIMEOUT
          value: {{ .Values.server.readTimeout | quote }}
        - name: SERVER_WRITE_TIMEOUT
          value: {{ .Values.server.writeTimeout | quote }}
        - name: SERVER_IDLE_TIMEOUT
          value: {{ .Values.server.idleTimeout | quote }}
        - name: SERVER_SHUTDOWN_TIMEOUT
          value: {{ .Values.server.shutdownTimeout | quote }}
        # PostgreSQL
        - name: DB_HOST
          value: {{ .Values.db.host | quote }}
        - name: DB_PORT
          value: {{ .Values.db.port | quote }}
        - name: DB_USER
          value: {{ .Values.db.user | quote }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.existingSecretName }}
              key: {{ .Values.db.existingSecretKey }}
        - name: DB_NAME
          value: {{ .Values.db.name | quote }}
        - name: DB_SSLMODE
          value: {{ .Values.db.sslMode | quote }}
        - name: DB_TIMEZONE
          value: {{ .Values.db.timeZone | quote }}
        - name: DB_MAX_OPEN_CONNS
          value: {{ .Values.db.maxOpenConns | quote }}
        - name: DB_MAX_IDLE_CONNS
          value: {{ .Values.db.maxIdleConns | quote }}
        - name: DB_CONN_MAX_LIFETIME
          value: {{ .Values.db.connMaxLifetime | quote }}
        # URL shortener
        - name: SHORTENER_BASE_URL
          value: {{ .Values.shortener.baseURL | quote }}
        - name: SHORTENER_API_KEYS
        {{- if .Values.shortener.apiKeysSecretName }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.shortener.apiKeysSecretName }}
              key: {{ .Values.shortener.apiKeysSecretKey }}
        {{- else }}
          value: {{ .Values.shortener.apiKeys | quote }}
        {{- end }}
        - name: SHORTENER_CODE_LENGTH
          value: {{ .Values.shortener.codeLength | quote }}
