{{- if .Values.bulkWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bulk-worker
spec:
  replicas: {{ .Values.bulkWorker.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-bulk-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-bulk-worker
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: bulk-worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["./main"]
        args: ["bulk-worker"]
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.existingSecretName }}
              key: {{ .Values.db.existingSecretKey }}
        - name: KAFKA_SASL_PASSWORD
        {{- if .Values.kafka.existingSecretName }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.kafka.existingSecretName }}
              key: {{ .Values.kafka.existingSecretKey }}
        {{- else }}
          value: ""
        {{- end }}
        - name: R2_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.r2.existingSecretName }}
              key: {{ .Values.r2.accessKeyIDKey }}
        - name: R2_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.r2.existingSecretName }}
              key: {{ .Values.r2.secretAccessKeyKey }}
{{- end }}
